### ISSUE TITLE
Privacy Issue

### ISSUE THREAD

**Issue by ghost** [1cgonza/gitbook-plugin-iframely#1]
If we enter API Key in the `book.json` file, the key would be leaked during inspecting the page by users.

**Comment by 1cgonza** [comment]
@haodong you are right, if the `book.json` is on a public repository, the API key will be visible. Since GitBook is a static site generator, I don't know how else to go about securing the key. I'll keep this open for now while I dig into this issue. PR are welcome either for a solution or alerting users of this in the documentation.

**Comment by ghost** [comment]
@1cgonza Even when the gitbook was generated from a private repo, the API key can still be visible in xpath `/html/body/div/script/text()`. It seems to be a gitbook's problem.

**Comment by ghost** [comment]
@1cgonza According to https://github.com/GitbookIO/feedback/issues/370, we can save API keys into environmental variables, just like what [Algolia](https://github.com/GitbookIO/plugin-algolia/) did.

**Comment by 1cgonza** [comment]
@haodong thanks for the pointer, I'll try to implement this as soon as I have the time. If you want to contribute a PR, feel free to do so. Otherwise I'll dive into this the next week or so.

**Comment by haodong** [comment]
Sure, I'll try my best in the next days.

**Comment by ghost** [comment]
@1cgonza I've submitted a PR https://github.com/1cgonza/gitbook-plugin-iframely/pull/2
